[package]
name = "raster"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
model.workspace = true
layout.workspace = true
analysis.workspace = true
language.workspace = true
fontdue = "=0.9.3"
sdfer = "=0.2.1"
blake3 = "1"
png = "0.17"
tempfile.workspace = true

[dev-dependencies]
serde_json.workspace = true
